kind = "DojoContract"
class_hash = "0x394b6a9219ec1e5e1e3afdec390794e017870eb56b58ad18252d3c1eaf2a0f0"
original_class_hash = "0x394b6a9219ec1e5e1e3afdec390794e017870eb56b58ad18252d3c1eaf2a0f0"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/bytebeasts-spawn_action-5176c1e8.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-spawn_action"
manifest_name = "bytebeasts-spawn_action-5176c1e8"
