kind = "DojoContract"
class_hash = "0x2f93ef02c13183550d5a6132cf31de73371f52670ad8cb9c3eaa5e2aeeabd43"
original_class_hash = "0x2f93ef02c13183550d5a6132cf31de73371f52670ad8cb9c3eaa5e2aeeabd43"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"
