kind = "DojoContract"
class_hash = "0x23660f8b5dd0b445a2edb889ea5c25b9a9116ef97ef15e9e93567a0bd801fdc"
original_class_hash = "0x23660f8b5dd0b445a2edb889ea5c25b9a9116ef97ef15e9e93567a0bd801fdc"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"
