[package]
cairo-version = "2.6.3"
name = "dojo_starter"
version = "0.7.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.1" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/bytebeast/katana"
# Default account for katana with seed = 0
account_address = "0x69562e297da25abcc1fd34e53b4a534e939fcc445f946e8d8d2bcb3e0e44e44"
private_key = "0x4710e214ec335128592d179195a0b52a641d32bdb780803f30f6ee5805783c4"
#world_address = "0xb4079627ebab1cd3cf9fd075dda1ad2454a7a448bf659591f259efa2519b18"  # Uncomment and update this line with your world address.

[tool.dojo.world]
name = "bytebeast"
description = "This is the Dojo implementation for Bytebeast"
