[package]
cairo-version = "2.6.3"
name = "dojo_starter"
version = "0.7.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.3" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/marco/katana"
# Default account for katana with seed = 0
account_address = "0x582021b1274d3a25c376c985e7bcb65d33969e40c05e3e09ec9a8dde465e54d"
private_key = "0xa7b80f0a434182514c99801ea62ed240c11fb6eb15f237bc48617a6456e6cf"

[tool.dojo.world]
name = "bytebeast"
description = "This is the Dojo implementation for Bytebeast"
