[package]
cairo-version = "=2.7.0"
name = "bytebeasts"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"
spawn = "./scripts/spawn.sh"
move = "./scripts/move.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.5" }
# Alexandria versions with tag greater that "cairo-v.5.4" conflict with dojo engine
alexandria_searching = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "cairo-v2.5.4" }
alexandria_sorting = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "cairo-v2.5.4" }

[[target.dojo]]
