[world]
kind = "WorldContract"
class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
original_class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x644001b28f89e7ae8a39f9c48eb4961cc4f817dc40b4b527f851a56fe703652"
transaction_hash = "0x1f1c658f1b3de98e21e98839833fb636773cf806eb7d2e3d3ec52e35c35a78"
block_number = 3
seed = "bytebeasts"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://0.0.0.0:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x4854bb6cc04b51e5adaed76afc0664091182fe44a9e5e68dc4f8f5f59ffd464"
class_hash = "0x7a662a2c7e8067fd633c3840f51c671a18c2e71901995fe791281c07c855aa0"
original_class_hash = "0x7a662a2c7e8067fd633c3840f51c671a18c2e71901995fe791281c07c855aa0"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/bytebeasts-actions-648ac931.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-actions"
manifest_name = "bytebeasts-actions-648ac931"

[[contracts]]
kind = "DojoContract"
address = "0x31d91cb20f41aa13507de40e2b7b5b85338e240388ea905ede7b799cafadcbe"
class_hash = "0x51aaf7a580665ebd6d7d32e2340f0e8b6850296fc1ad389c74a293d1a26029f"
original_class_hash = "0x51aaf7a580665ebd6d7d32e2340f0e8b6850296fc1ad389c74a293d1a26029f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/bytebeasts-bag_system-7ad8a155.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-bag_system"
manifest_name = "bytebeasts-bag_system-7ad8a155"

[[contracts]]
kind = "DojoContract"
address = "0x612b684f6b34356ad9a07ac3e1924f9dfa54235d0a513095b0d12695ace8b68"
class_hash = "0x22eff2287b74c9f79832f32132c8154f28f916551d8650c8425f6c1c49adc31"
original_class_hash = "0x22eff2287b74c9f79832f32132c8154f28f916551d8650c8425f6c1c49adc31"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/bytebeasts-battle_system-461868ac.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-battle_system"
manifest_name = "bytebeasts-battle_system-461868ac"

[[contracts]]
kind = "DojoContract"
address = "0x6e214ac3592bdfbc7d2df77bac600e11786a1af5995f9b8422ba11a7ca105c7"
class_hash = "0x6ab57932e6f1d360557867a6775d89180d623a481695d4349f6d356c8cd31ee"
original_class_hash = "0x6ab57932e6f1d360557867a6775d89180d623a481695d4349f6d356c8cd31ee"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/bytebeasts-move_action-62decdb8.json"
reads = []
writes = ["bytebeasts-Position"]
init_calldata = []
tag = "bytebeasts-move_action"
manifest_name = "bytebeasts-move_action-62decdb8"

[[contracts]]
kind = "DojoContract"
address = "0x3069906b1afcae5bc379fb0e7e8aad2aa249be91229aab7d96c608bc2136f18"
class_hash = "0x394b6a9219ec1e5e1e3afdec390794e017870eb56b58ad18252d3c1eaf2a0f0"
original_class_hash = "0x394b6a9219ec1e5e1e3afdec390794e017870eb56b58ad18252d3c1eaf2a0f0"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/bytebeasts-spawn_action-5176c1e8.json"
reads = []
writes = [
    "bytebeasts-Beast",
    "bytebeasts-Mt",
    "bytebeasts-Player",
    "bytebeasts-Potion",
    "bytebeasts-Position",
]
init_calldata = []
tag = "bytebeasts-spawn_action"
manifest_name = "bytebeasts-spawn_action-5176c1e8"

[[contracts]]
kind = "DojoContract"
address = "0x1a0997571ba63300bba592512cc9ac1daa8911ee08c049b5693d93c06377d25"
class_hash = "0xad9d2da0783e3a31f6198d7c355bd293e496019e0e335449377a2c0146880"
original_class_hash = "0xad9d2da0783e3a31f6198d7c355bd293e496019e0e335449377a2c0146880"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/bytebeasts-world_setup-674b640b.json"
reads = []
writes = [
    "bytebeasts-Beast",
    "bytebeasts-Mt",
    "bytebeasts-Player",
    "bytebeasts-Potion",
    "bytebeasts-Position",
]
init_calldata = []
tag = "bytebeasts-world_setup"
manifest_name = "bytebeasts-world_setup-674b640b"

[[models]]
kind = "DojoModel"
class_hash = "0x41f50347f6f957bc556346a2cdea3f31523f3c25966826e7ca7dea1de185c40"
original_class_hash = "0x41f50347f6f957bc556346a2cdea3f31523f3c25966826e7ca7dea1de185c40"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Achievement-58a03b97.json"
tag = "bytebeasts-Achievement"
manifest_name = "bytebeasts-Achievement-58a03b97"

[[models.members]]
name = "achievement_id"
type = "u64"
key = true

[[models.members]]
name = "achievement_type"
type = "AchievementType"
key = false

[[models.members]]
name = "rarity"
type = "AchievementRarity"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "description"
type = "ByteArray"
key = false

[[models.members]]
name = "is_hidden"
type = "bool"
key = false

[[models.members]]
name = "is_unlocked"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x494e5a6534846cd68b493aab6f9954333c64c854dbe99144c427f4301477f15"
original_class_hash = "0x494e5a6534846cd68b493aab6f9954333c64c854dbe99144c427f4301477f15"
abi = "manifests/dev/deployment/abis/models/bytebeasts-AchievementProgress-221f2719.json"
tag = "bytebeasts-AchievementProgress"
manifest_name = "bytebeasts-AchievementProgress-221f2719"

[[models.members]]
name = "player_id"
type = "u64"
key = true

[[models.members]]
name = "achievement_id"
type = "u64"
key = false

[[models.members]]
name = "progress"
type = "u32"
key = false

[[models.members]]
name = "is_unlocked"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4e0fab7bc052de0008be5606ad3b37576afd2bda323443fc98a8f37bcc10c1c"
original_class_hash = "0x4e0fab7bc052de0008be5606ad3b37576afd2bda323443fc98a8f37bcc10c1c"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Bag-2571b77d.json"
tag = "bytebeasts-Bag"
manifest_name = "bytebeasts-Bag-2571b77d"

[[models.members]]
name = "bag_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "u32"
key = true

[[models.members]]
name = "max_capacity"
type = "u32"
key = false

[[models.members]]
name = "potions"
type = "Array<Potion>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x239c54e950b5c50d445f9a8db758ea0af1440b75a5f1921dfe014b927476c32"
original_class_hash = "0x239c54e950b5c50d445f9a8db758ea0af1440b75a5f1921dfe014b927476c32"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Battle-55b5860b.json"
tag = "bytebeasts-Battle"
manifest_name = "bytebeasts-Battle-55b5860b"

[[models.members]]
name = "battle_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "u32"
key = false

[[models.members]]
name = "opponent_id"
type = "u32"
key = false

[[models.members]]
name = "active_beast_player"
type = "u32"
key = false

[[models.members]]
name = "active_beast_opponent"
type = "u32"
key = false

[[models.members]]
name = "battle_active"
type = "u32"
key = false

[[models.members]]
name = "turn"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7bef5c17e52dab476cd7ae664bbb0f0024aae955ed8b12592e2d6faf7ff6a3c"
original_class_hash = "0x7bef5c17e52dab476cd7ae664bbb0f0024aae955ed8b12592e2d6faf7ff6a3c"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Beast-27809d20.json"
tag = "bytebeasts-Beast"
manifest_name = "bytebeasts-Beast-27809d20"

[[models.members]]
name = "beast_id"
type = "u32"
key = true

[[models.members]]
name = "beast_name"
type = "felt252"
key = false

[[models.members]]
name = "beast_type"
type = "WorldElements"
key = false

[[models.members]]
name = "beast_description"
type = "felt252"
key = false

[[models.members]]
name = "player_id"
type = "u32"
key = false

[[models.members]]
name = "hp"
type = "u32"
key = false

[[models.members]]
name = "current_hp"
type = "u32"
key = false

[[models.members]]
name = "attack"
type = "u32"
key = false

[[models.members]]
name = "defense"
type = "u32"
key = false

[[models.members]]
name = "mt1"
type = "u32"
key = false

[[models.members]]
name = "mt2"
type = "u32"
key = false

[[models.members]]
name = "mt3"
type = "u32"
key = false

[[models.members]]
name = "mt4"
type = "u32"
key = false

[[models.members]]
name = "level"
type = "u32"
key = false

[[models.members]]
name = "experience_to_next_level"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x57c477846284e274054c78c5b265af51f8815abbf0147828080c274b0639764"
original_class_hash = "0x57c477846284e274054c78c5b265af51f8815abbf0147828080c274b0639764"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Game-e91217d7.json"
tag = "bytebeasts-Game"
manifest_name = "bytebeasts-Game-e91217d7"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_1"
type = "ContractAddress"
key = false

[[models.members]]
name = "player_2"
type = "ContractAddress"
key = false

[[models.members]]
name = "player_3"
type = "ContractAddress"
key = false

[[models.members]]
name = "player_4"
type = "ContractAddress"
key = false

[[models.members]]
name = "status"
type = "GameStatus"
key = false

[[models.members]]
name = "is_private"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7dc1689aa3f1e6b123cadfed4066a70f09be69c9a166bfe824c61b916925efe"
original_class_hash = "0x7dc1689aa3f1e6b123cadfed4066a70f09be69c9a166bfe824c61b916925efe"
abi = "manifests/dev/deployment/abis/models/bytebeasts-GameId-344511d3.json"
tag = "bytebeasts-GameId"
manifest_name = "bytebeasts-GameId-344511d3"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "game_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x52df62dec799bbf7ba4725f74e32e579dec2d90a7a995638761646157bb7e18"
original_class_hash = "0x52df62dec799bbf7ba4725f74e32e579dec2d90a7a995638761646157bb7e18"
abi = "manifests/dev/deployment/abis/models/bytebeasts-GamePlayer-596ef4a1.json"
tag = "bytebeasts-GamePlayer"
manifest_name = "bytebeasts-GamePlayer-596ef4a1"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "beast_1"
type = "u8"
key = false

[[models.members]]
name = "beast_2"
type = "u8"
key = false

[[models.members]]
name = "beast_3"
type = "u8"
key = false

[[models.members]]
name = "beast_4"
type = "u8"
key = false

[[models.members]]
name = "bag_id"
type = "u8"
key = false

[[models.members]]
name = "active_mount"
type = "u8"
key = false

[[models.members]]
name = "mounts"
type = "Array<u8>"
key = false

[[models.members]]
name = "position"
type = "Array<u8>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x341a07493baed313e741253a241aa31fc9d40a9c373cd2bae49f85ab66f98cc"
original_class_hash = "0x341a07493baed313e741253a241aa31fc9d40a9c373cd2bae49f85ab66f98cc"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Mt-37360d30.json"
tag = "bytebeasts-Mt"
manifest_name = "bytebeasts-Mt-37360d30"

[[models.members]]
name = "mt_id"
type = "u32"
key = true

[[models.members]]
name = "mt_name"
type = "felt252"
key = false

[[models.members]]
name = "mt_type"
type = "WorldElements"
key = false

[[models.members]]
name = "mt_power"
type = "u32"
key = false

[[models.members]]
name = "mt_accuracy"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3ba44df67a037c20f004b7f5ab7725932d4519eed6beb6bc223a03e96c0f0f9"
original_class_hash = "0x3ba44df67a037c20f004b7f5ab7725932d4519eed6beb6bc223a03e96c0f0f9"
abi = "manifests/dev/deployment/abis/models/bytebeasts-NPC-4c5239ac.json"
tag = "bytebeasts-NPC"
manifest_name = "bytebeasts-NPC-4c5239ac"

[[models.members]]
name = "npc_id"
type = "u32"
key = true

[[models.members]]
name = "npc_name"
type = "felt252"
key = false

[[models.members]]
name = "npc_description"
type = "felt252"
key = false

[[models.members]]
name = "npc_role"
type = "Role"
key = false

[[models.members]]
name = "dialogue"
type = "ByteArray"
key = false

[[models.members]]
name = "is_active"
type = "bool"
key = false

[[models.members]]
name = "location"
type = "Coordinates"
key = false

[[models.members]]
name = "importance_level"
type = "u8"
key = false

[[models.members]]
name = "mission_status"
type = "MissionStatus"
key = false

[[models.members]]
name = "reward"
type = "u16"
key = false

[[models.members]]
name = "experience_points"
type = "u16"
key = false

[[models.members]]
name = "potions"
type = "Array<Potion>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5d992305e6f7ce0965d5bbe71e33cab817c31514ba83c8fca4610ab574e8016"
original_class_hash = "0x5d992305e6f7ce0965d5bbe71e33cab817c31514ba83c8fca4610ab574e8016"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Player-14f5e45e.json"
tag = "bytebeasts-Player"
manifest_name = "bytebeasts-Player-14f5e45e"

[[models.members]]
name = "player_id"
type = "u32"
key = true

[[models.members]]
name = "player_name"
type = "felt252"
key = false

[[models.members]]
name = "beast_1"
type = "u32"
key = false

[[models.members]]
name = "beast_2"
type = "u32"
key = false

[[models.members]]
name = "beast_3"
type = "u32"
key = false

[[models.members]]
name = "beast_4"
type = "u32"
key = false

[[models.members]]
name = "potions"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x91da9f380b960e2dc7f9a59d4e1242ed718590d2270fd28e2311a5e1ee54f2"
original_class_hash = "0x91da9f380b960e2dc7f9a59d4e1242ed718590d2270fd28e2311a5e1ee54f2"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Position-78f28df6.json"
tag = "bytebeasts-Position"
manifest_name = "bytebeasts-Position-78f28df6"

[[models.members]]
name = "player"
type = "Player"
key = true

[[models.members]]
name = "coordinates"
type = "Coordinates"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4eac23f35a0e71954b8f000d9d8999579ba49ffc918e8b78924562449bdf8d4"
original_class_hash = "0x4eac23f35a0e71954b8f000d9d8999579ba49ffc918e8b78924562449bdf8d4"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Potion-6a2114b0.json"
tag = "bytebeasts-Potion"
manifest_name = "bytebeasts-Potion-6a2114b0"

[[models.members]]
name = "potion_id"
type = "u32"
key = true

[[models.members]]
name = "potion_name"
type = "felt252"
key = false

[[models.members]]
name = "potion_effect"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xe446a8c3773fbfae6e2e0e87a6d1db12143224cf47e217e12bf9cfc76428ef"
original_class_hash = "0xe446a8c3773fbfae6e2e0e87a6d1db12143224cf47e217e12bf9cfc76428ef"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Status-6595af0f.json"
tag = "bytebeasts-Status"
manifest_name = "bytebeasts-Status-6595af0f"

[[models.members]]
name = "player_id"
type = "u32"
key = true

[[models.members]]
name = "message"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5ba495f80b653be6df964eb97ac2e7b3f7f72508d17b54b1d51595231db8fae"
original_class_hash = "0x5ba495f80b653be6df964eb97ac2e7b3f7f72508d17b54b1d51595231db8fae"
abi = "manifests/dev/deployment/abis/models/bytebeasts-StatusBattle-161fdb64.json"
tag = "bytebeasts-StatusBattle"
manifest_name = "bytebeasts-StatusBattle-161fdb64"

[[models.members]]
name = "battle_id"
type = "u32"
key = true

[[models.members]]
name = "message"
type = "felt252"
key = false
