[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0xb4079627ebab1cd3cf9fd075dda1ad2454a7a448bf659591f259efa2519b18"
transaction_hash = "0x4b6f028e019c8db1a07e76a6183b677fba9cac8d269220207da8b9c06514638"
block_number = 3
seed = "dojo_starter"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://0.0.0.0:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x3610b797baec740e2fa25ae90b4a57d92b04f48a1fdbae1ae203eaf9723c1a0"
class_hash = "0x62254e09a7226bef2d537974fb5338a153febfdb699218b26028eaecafe542b"
original_class_hash = "0x62254e09a7226bef2d537974fb5338a153febfdb699218b26028eaecafe542b"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = [
    "Position",
    "Moves",
    "DirectionsAvailable",
]
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x68f7051deaeeee8db9adabd790cf1f83e27a00ac7d9988e2ed6dbfa9a63751"
original_class_hash = "0x68f7051deaeeee8db9adabd790cf1f83e27a00ac7d9988e2ed6dbfa9a63751"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_beast_beast.json"
name = "dojo_starter::models::beast::beast"

[[models.members]]
name = "beast_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = false

[[models.members]]
name = "beast_type"
type = "BeastType"
key = false

[[models.members]]
name = "hp"
type = "u64"
key = false

[[models.members]]
name = "mp"
type = "u64"
key = false

[[models.members]]
name = "strength"
type = "u64"
key = false

[[models.members]]
name = "defense"
type = "u64"
key = false

[[models.members]]
name = "equipped_weapon"
type = "felt252"
key = false

[[models.members]]
name = "wpn_power"
type = "u8"
key = false

[[models.members]]
name = "equipped_armor"
type = "felt252"
key = false

[[models.members]]
name = "armor_power"
type = "u64"
key = false

[[models.members]]
name = "experience_to_nex_level"
type = "u64"
key = false

[[models.members]]
name = "level"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x13fc796dd2d767ca4051ee20d673074f74b6e6b072bef1926ba429e427c8080"
original_class_hash = "0x13fc796dd2d767ca4051ee20d673074f74b6e6b072bef1926ba429e427c8080"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_moves_directions_available.json"
name = "dojo_starter::models::moves::directions_available"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "directions"
type = "Array<Direction>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2f6c0529a3aa4c81c1679408106b2c00013fc19a7088ed9639046c0e3aeac7a"
original_class_hash = "0x2f6c0529a3aa4c81c1679408106b2c00013fc19a7088ed9639046c0e3aeac7a"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_moves_moves.json"
name = "dojo_starter::models::moves::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models.members]]
name = "can_move"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4312e0e9fa6d912c293311798591e5022744a5fbebefc5ddfcfcc9b7c0c9be1"
original_class_hash = "0x4312e0e9fa6d912c293311798591e5022744a5fbebefc5ddfcfcc9b7c0c9be1"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_position_position.json"
name = "dojo_starter::models::position::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x63059e8ec335b1632218371a88fbd633d4d7201e15d65920d0f054bd37b80a"
original_class_hash = "0x63059e8ec335b1632218371a88fbd633d4d7201e15d65920d0f054bd37b80a"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_user_user.json"
name = "dojo_starter::models::user::user"

[[models.members]]
name = "user_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1e1fa676a44c4b22fe024f3d3a681904fc4fcaececd382b94d794593b811de2"
original_class_hash = "0x1e1fa676a44c4b22fe024f3d3a681904fc4fcaececd382b94d794593b811de2"
abi = "manifests/dev/abis/deployments/models/dojo_starter_systems_actions_actions_moved.json"
name = "dojo_starter::systems::actions::actions::moved"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false
