kind = "DojoModel"
class_hash = "0x551cf89bdd06c5be266b0260c53cc9740563e6b82dc6f52bd27bf3353577c3e"
original_class_hash = "0x551cf89bdd06c5be266b0260c53cc9740563e6b82dc6f52bd27bf3353577c3e"
abi = "manifests/dev/base/abis/models/bytebeasts-Leaderboard-7e680376.json"
tag = "bytebeasts-Leaderboard"
manifest_name = "bytebeasts-Leaderboard-7e680376"

[[members]]
name = "leaderboard_id"
type = "u64"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "description"
type = "felt252"
key = false

[[members]]
name = "entries"
type = "Array<LeaderboardEntry>"
key = false

[[members]]
name = "last_updated"
type = "u64"
key = false
