kind = "DojoModel"
class_hash = "0x7a8bee9882da24371365f5e6531ed532e9deb91c5b5173d7d230dec53c5c337"
original_class_hash = "0x7a8bee9882da24371365f5e6531ed532e9deb91c5b5173d7d230dec53c5c337"
abi = "manifests/dev/base/abis/models/bytebeasts-Season-52f8bbb6.json"
tag = "bytebeasts-Season"
manifest_name = "bytebeasts-Season-52f8bbb6"

[[members]]
name = "season_id"
type = "u64"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "start_date"
type = "u64"
key = false

[[members]]
name = "end_date"
type = "u64"
key = false

[[members]]
name = "is_active"
type = "bool"
key = false

[[members]]
name = "active_players"
type = "Array<u64>"
key = false
