kind = "DojoModel"
class_hash = "0x3ba44df67a037c20f004b7f5ab7725932d4519eed6beb6bc223a03e96c0f0f9"
original_class_hash = "0x3ba44df67a037c20f004b7f5ab7725932d4519eed6beb6bc223a03e96c0f0f9"
abi = "manifests/dev/base/abis/models/bytebeasts-NPC-4c5239ac.json"
tag = "bytebeasts-NPC"
manifest_name = "bytebeasts-NPC-4c5239ac"

[[members]]
name = "npc_id"
type = "u32"
key = true

[[members]]
name = "npc_name"
type = "felt252"
key = false

[[members]]
name = "npc_description"
type = "felt252"
key = false

[[members]]
name = "npc_role"
type = "Role"
key = false

[[members]]
name = "dialogue"
type = "ByteArray"
key = false

[[members]]
name = "is_active"
type = "bool"
key = false

[[members]]
name = "location"
type = "Coordinates"
key = false

[[members]]
name = "importance_level"
type = "u8"
key = false

[[members]]
name = "mission_status"
type = "MissionStatus"
key = false

[[members]]
name = "reward"
type = "u16"
key = false

[[members]]
name = "experience_points"
type = "u16"
key = false

[[members]]
name = "potions"
type = "Array<Potion>"
key = false
