kind = "DojoModel"
class_hash = "0x4e0fab7bc052de0008be5606ad3b37576afd2bda323443fc98a8f37bcc10c1c"
original_class_hash = "0x4e0fab7bc052de0008be5606ad3b37576afd2bda323443fc98a8f37bcc10c1c"
abi = "manifests/dev/base/abis/models/bytebeasts-Bag-2571b77d.json"
tag = "bytebeasts-Bag"
manifest_name = "bytebeasts-Bag-2571b77d"

[[members]]
name = "bag_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "max_capacity"
type = "u32"
key = false

[[members]]
name = "potions"
type = "Array<Potion>"
key = false
