kind = "DojoModel"
class_hash = "0x494e5a6534846cd68b493aab6f9954333c64c854dbe99144c427f4301477f15"
original_class_hash = "0x494e5a6534846cd68b493aab6f9954333c64c854dbe99144c427f4301477f15"
abi = "manifests/dev/base/abis/models/bytebeasts-AchievementProgress-221f2719.json"
tag = "bytebeasts-AchievementProgress"
manifest_name = "bytebeasts-AchievementProgress-221f2719"

[[members]]
name = "player_id"
type = "u64"
key = true

[[members]]
name = "achievement_id"
type = "u64"
key = false

[[members]]
name = "progress"
type = "u32"
key = false

[[members]]
name = "is_unlocked"
type = "bool"
key = false
