kind = "DojoModel"
class_hash = "0xb026d19ae870649f8cab89b1192f93314aa48a7f6cfdeea487f9eaf89bf430"
original_class_hash = "0xb026d19ae870649f8cab89b1192f93314aa48a7f6cfdeea487f9eaf89bf430"
abi = "manifests/dev/abis/base/models/bytebeastsbeta_models_entities_beast_beast.json"
name = "bytebeastsbeta::models::entities::beast::beast"

[[members]]
name = "beast_id"
type = "u32"
key = true

[[members]]
name = "beast_type"
type = "u8"
key = false

[[members]]
name = "hp"
type = "u64"
key = false

[[members]]
name = "attack"
type = "u64"
key = false

[[members]]
name = "movement_range"
type = "u64"
key = false
