kind = "DojoModel"
class_hash = "0x41f50347f6f957bc556346a2cdea3f31523f3c25966826e7ca7dea1de185c40"
original_class_hash = "0x41f50347f6f957bc556346a2cdea3f31523f3c25966826e7ca7dea1de185c40"
abi = "manifests/dev/base/abis/models/bytebeasts-Achievement-58a03b97.json"
tag = "bytebeasts-Achievement"
manifest_name = "bytebeasts-Achievement-58a03b97"

[[members]]
name = "achievement_id"
type = "u64"
key = true

[[members]]
name = "achievement_type"
type = "AchievementType"
key = false

[[members]]
name = "rarity"
type = "AchievementRarity"
key = false

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "description"
type = "ByteArray"
key = false

[[members]]
name = "is_hidden"
type = "bool"
key = false

[[members]]
name = "is_unlocked"
type = "bool"
key = false
