kind = "DojoModel"
class_hash = "0x7e8eaf987baca059fe8822fb86bd596e9f00c2f72cb4e39d3f7a51cfd79a2ab"
original_class_hash = "0x7e8eaf987baca059fe8822fb86bd596e9f00c2f72cb4e39d3f7a51cfd79a2ab"
abi = "manifests/dev/abis/base/models/dojo_starter_models_beast_beast.json"
name = "dojo_starter::models::beast::beast"

[[members]]
name = "beast_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "ContractAddress"
key = false

[[members]]
name = "beast_type"
type = "BeastType"
key = false

[[members]]
name = "hp"
type = "u32"
key = false

[[members]]
name = "mp"
type = "u64"
key = false

[[members]]
name = "strength"
type = "u64"
key = false

[[members]]
name = "defense"
type = "u64"
key = false

[[members]]
name = "equipped_weapon"
type = "felt252"
key = false

[[members]]
name = "wpn_power"
type = "u8"
key = false

[[members]]
name = "equipped_armor"
type = "felt252"
key = false

[[members]]
name = "armor_power"
type = "u64"
key = false

[[members]]
name = "experience_to_nex_level"
type = "u64"
key = false

[[members]]
name = "level"
type = "u8"
key = false
