kind = "DojoModel"
class_hash = "0x68f7051deaeeee8db9adabd790cf1f83e27a00ac7d9988e2ed6dbfa9a63751"
original_class_hash = "0x68f7051deaeeee8db9adabd790cf1f83e27a00ac7d9988e2ed6dbfa9a63751"
abi = "manifests/dev/abis/base/models/dojo_starter_models_beast_beast.json"
name = "dojo_starter::models::beast::beast"

[[members]]
name = "beast_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "ContractAddress"
key = false

[[members]]
name = "beast_type"
type = "BeastType"
key = false

[[members]]
name = "hp"
type = "u64"
key = false

[[members]]
name = "mp"
type = "u64"
key = false

[[members]]
name = "strength"
type = "u64"
key = false

[[members]]
name = "defense"
type = "u64"
key = false

[[members]]
name = "equipped_weapon"
type = "felt252"
key = false

[[members]]
name = "wpn_power"
type = "u8"
key = false

[[members]]
name = "equipped_armor"
type = "felt252"
key = false

[[members]]
name = "armor_power"
type = "u64"
key = false

[[members]]
name = "experience_to_nex_level"
type = "u64"
key = false

[[members]]
name = "level"
type = "u8"
key = false
