kind = "DojoModel"
class_hash = "0x6f2ab954389d07486646883c96410be229d5261bf02a398a3b6e58e0fb953df"
original_class_hash = "0x6f2ab954389d07486646883c96410be229d5261bf02a398a3b6e58e0fb953df"
abi = "manifests/dev/abis/base/models/dojo_starter_models_beast_beast.json"
name = "dojo_starter::models::beast::beast"

[[members]]
name = "beast_id"
type = "felt252"
key = true

[[members]]
name = "player_id"
type = "ContractAddress"
key = false

[[members]]
name = "beast_type"
type = "felt252"
key = false

[[members]]
name = "hp"
type = "u32"
key = false

[[members]]
name = "currentHp"
type = "u32"
key = false

[[members]]
name = "mp"
type = "u64"
key = false

[[members]]
name = "currentMp"
type = "u64"
key = false

[[members]]
name = "strength"
type = "u64"
key = false

[[members]]
name = "defense"
type = "u64"
key = false

[[members]]
name = "equipped_weapon"
type = "felt252"
key = false

[[members]]
name = "wpn_power"
type = "u8"
key = false

[[members]]
name = "equipped_armor"
type = "felt252"
key = false

[[members]]
name = "armor_power"
type = "u64"
key = false

[[members]]
name = "experience_to_nex_level"
type = "u64"
key = false
