// Generated by dojo-bindgen on Fri, 5 Jul 2024 13:09:26 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `dojo_starter::models::beast::Beast` model
public class Beast : ModelInstance {
    [ModelField("beast_id")]
    public uint beast_id;

    [ModelField("player_id")]
    public FieldElement player_id;

    [ModelField("beast_type")]
    public FieldElement beast_type;

    [ModelField("hp")]
    public uint hp;

    [ModelField("currentHp")]
    public uint currentHp;

    [ModelField("mp")]
    public ulong mp;

    [ModelField("currentMp")]
    public ulong currentMp;

    [ModelField("strength")]
    public ulong strength;

    [ModelField("defense")]
    public ulong defense;

    [ModelField("equipped_weapon")]
    public FieldElement equipped_weapon;

    [ModelField("wpn_power")]
    public byte wpn_power;

    [ModelField("equipped_armor")]
    public FieldElement equipped_armor;

    [ModelField("armor_power")]
    public ulong armor_power;

    [ModelField("experience_to_nex_level")]
    public ulong experience_to_nex_level;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        