// Generated by dojo-bindgen on Fri, 5 Jul 2024 19:07:48 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_starter::models::moves::Direction` enum
public abstract record Direction() : Enum {
    public record None() : Direction;
    public record Left() : Direction;
    public record Right() : Direction;
    public record Up() : Direction;
    public record Down() : Direction;
}


// Model definition for `dojo_starter::systems::actions::actions::Moved` model
public class Moved : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("direction")]
    public Direction direction;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        