// Generated by dojo-bindgen on Fri, 21 Jun 2024 20:45:31 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `dojo_starter::models::moves::Moves` model
public class Moves : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("remaining")]
    public byte remaining;

    [ModelField("last_direction")]
    public Direction last_direction;

    [ModelField("can_move")]
    public bool can_move;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        