// Generated by dojo-bindgen on Fri, 5 Jul 2024 19:07:48 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_starter::models::position::Vec2` struct
[Serializable]
public struct Vec2 {
    public uint x;
    public uint y;
}

// Type definition for `core::byte_array::ByteArray` struct
[Serializable]
public struct ByteArray {
    public string[] data;
    public FieldElement pending_word;
    public uint pending_word_len;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
public abstract record Option<A>() : Enum {
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}


// Model definition for `dojo_starter::models::position::Position` model
public class Position : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("vec")]
    public Vec2 vec;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        